/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.padraoobserver;

import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author 20211STADS024
 */
public class DisplayTemperatura extends javax.swing.JPanel implements Observer {

    Observable dadosSensor;

    public DisplayTemperatura(Observable dadosSensor) {
        initComponents();
        this.dadosSensor = dadosSensor;
        dadosSensor.addObserver(this);
    }

    public DisplayTemperatura() {
        initComponents();
    }

    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtTemperatura;

    public void setTxtTemperatura(String txtTemperatura) {
        this.txtTemperatura.setText(txtTemperatura);
    }

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof SensorDeTemperatura) {
            SensorDeTemperatura sdt = (SensorDeTemperatura) o;
            this.txtTemperatura.setText(Integer.toString(sdt.getTemperatura));
            this.setVisible(true);
        }
    }

    private void initComponents() {

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//
/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DisplayTemperatura().setVisible(true);
        });
    }
}

/**
 * Creates new form DisplayTemperatura
 */
/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.padraoobserver;

/**
 *
 * @author 20211STADS024
 */
